### ISSUE TITLE
Latex Makefile shoud support bibtex

### ISSUE THREAD

**Issue by juliendelplanque** [dannywillems/Makefiles#2]
When you use a bibliography, you need bibtex. The process to compile a latex document using bibtex is the following:

1. pdflatex latex_file
2. bibtex bib_file
3. pdflatex latex_file
4. pdflatex latex_file

**Comment by dannywillems** [comment]
I worked on it some weeks ago. I will push these modifications.

**Comment by juliendelplanque** [comment]
Thanks I need that, for the moment I replaced my Makefile with a bash file that does the job ( which is sad but I have no time to lose in that and I am not a Makefile expert...).

**Comment by dannywillems** [comment]
@juliendelplanque What I did is very ugly: I prefer to polish when I will need it again (soon). In general, I need to rewrite all makefiles because they are very ugly.

**Comment by juliendelplanque** [comment]
I prefer to have it ugly and working than not having the feature...

**Comment by dannywillems** [comment]
@juliendelplanque It's not my case.

**Comment by juliendelplanque** [comment]
Ok but then, I'll stay on my bash script which may be ugly but is working well.
